name: Tests

on:
  workflow_dispatch:

jobs:
  generate-anycharm-json-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python3 - <<'____HERE' > ${{ github.workspwce }}/haproxy_route_requirer_src.json
          import json
          import pathlib
          json.dumps(
            {
              "any_charm.py": pathlib.Path("tests/integration/haproxy_route_requirer.py").read_text(
                encoding="utf-8"
              ),
              "haproxy_route.py": pathlib.Path("lib/charms/haproxy/v0/haproxy_route.py").read_text(
                encoding="utf-8"
              ),
            }
          )
          ____HERE
      - uses: actions/upload-artifact@v4
        with:
          name: haproxy_route_requirer_src
          path: ${{ github.workspwce }}/haproxy_route_requirer_src.json
