name: Tests

on:
  workflow_dispatch:

jobs:
  generate-anycharm-json-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls -la
          echo $GITHUB_WORKSPACE
          python3 - <<'____HERE' > /tmp/haproxy_route_requirer_src.json
          import json
          import pathlib
          import os

          workspace = os.environ["GITHUB_WORKSPACE"]
          json.dumps(
            {
              "any_charm.py": pathlib.Path(f"{workspace}/tests/integration/haproxy_route_requirer.py").read_text(
                encoding="utf-8"
              ),
              "haproxy_route.py": pathlib.Path(f"{workspace}/lib/charms/haproxy/v0/haproxy_route.py").read_text(
                encoding="utf-8"
              ),
            }
          )
          ____HERE
      - uses: actions/upload-artifact@v4
        with:
          name: haproxy_route_requirer_src
          path: /tmp/haproxy_route_requirer_src.json
